version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-{{ checksum "package.json" }}
      - run:
          name: Install 
          command: yarn 
      - save_cache:
          key: project-{{ checksum "package.json" }}
          paths:
            - ~/project/node_modules
      - run:
          name: Build 
          environment:
            DS_ENV: production
          command: yarn build
      - run:
          name: Build and Deploy to Heroku
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              yarn surge
            fi