version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-{{ checksum "package.json" }}
      - run:
          name: Install 
          command: yarn 
      - save_cache:
          key: project-{{ checksum "package.json" }}
          paths:
            - ~/project/node_modules
      - run:
          name: Build 
          command: yarn build
      - add_ssh_keys:
          fingerprints:
            - "dd:6a:88:53:39:db:cd:5d:49:21:84:09:b1:b8:6b:1e"
      - run:
          name: Build and Deploy to Heroku
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              echo "Get ready, we're pushing to gh-pages!"
              cd dist
              echo "www.workelections.com" > CNAME
              git init
              git config user.name "circleci"
              git config user.email "info@developmetnseed.org"
              git add .
              git commit -m "CI deploy to gh-pages"
              git push --force --quiet git@github.com:developmentseed/work.vote.git master:gh-pages
            fi